//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PettiInn.DAL.Entities.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator : EntityBase, IName, ICreatedOn
    {
        public Administrator()
        {
            this.RoomBookings = new HashSet<RoomBooking>();
            this.Roles = new HashSet<Role>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastLoggedIn { get; set; }
        public bool IsSuper { get; set; }
    
        public virtual ICollection<RoomBooking> RoomBookings { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
