//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PettiInn.DAL.Entities.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module : EntityBase, IName, ISort
    {
        public Module()
        {
            this.Children = new HashSet<Module>();
            this.Roles = new HashSet<Role>();
        }
    
        public string Name { get; set; }
        public string CSS { get; set; }
        public string Class { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsSuper { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<Module> Children { get; set; }
        public virtual Module Parent { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
