//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PettiInn.DAL.Entities.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel : EntityBase, IName, ISort
    {
        public Hotel()
        {
            this.Prices = new HashSet<Price>();
            this.Rooms = new HashSet<Room>();
            this.RoomBookings = new HashSet<RoomBooking>();
            this.RoomTypeImages = new HashSet<RoomTypeImage>();
            this.RoomTypes = new HashSet<RoomType>();
        }
    
        public string Name { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<RoomBooking> RoomBookings { get; set; }
        public virtual ICollection<RoomTypeImage> RoomTypeImages { get; set; }
        public virtual ICollection<RoomType> RoomTypes { get; set; }
    }
}
