//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PettiInn.DAL.Entities.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role : EntityBase, IName
    {
        public Role()
        {
            this.Administrators = new HashSet<Administrator>();
            this.Modules = new HashSet<Module>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<Administrator> Administrators { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
    }
}
